# Generated by Django 5.2.15 on 2026-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_student_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
