"""add course_schedule table

Revision ID: 8eb43984c7e3
Revises: af8b314e14fa
Create Date: 2026-07-05 15:18:25.782381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb43984c7e3'
down_revision: Union[str, Sequence[str], None] = 'af8b314e14fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=15), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_schedules')
    # ### end Alembic commands ###
