# Generated by Django 5.2.15 on 2026-06-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment_enrollment_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="enrollment_year",
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
